source 'https://rubygems.org'

gem 'rails'
# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
gem 'high_voltage', '~> 2.2.1'
gem "rails3-generators"
gem 'mysql2'
gem "nifty-generators", :group => :development
#gem 'authlogic', :git => 'git://github.com/odorcicd/authlogic.git', 
#:branch => 'rails3'
gem 'authlogic', :git => 'git://github.com/binarylogic/authlogic.git'

gem 'execjs'
gem 'therubyrhino'
#gem 'therubyracer', :git => 'https://github.com/cowboyd/therubyracer.git'
#gem "therubyracer", :require => 'v8'
#gem "therubyracer", "~> 0.8.2.pre" #bleeding edge.


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier'
end

gem 'jquery-rails'


# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

gem "mocha", :group => :test
